name: super_converter
description: Simple convert anything to anything. As long as it has the required data to be converter it should be done automatically

version: 1.0.0

homepage: https://github.com/ismaelAbogabal/super_converter

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  intl: any

dev_dependencies:
  test: ^1.23.1
  flutter_lints: ^2.0.1


flutter:
